---
- hosts: nexus
  remote_user: vagrant
  become: yes
  
  tasks:
    - name: Copy certificate file from Nexus host to local
      fetch:
        src: "{{ nexus_ssl_cert_file }}"
        dest: "/tmp"

- hosts: jenkins
  remote_user: vagrant
  become: yes
  
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_install_compose: true
    docker_compose_version: "1.24.0-rc1"
    docker_users:
      - jenkins

  roles:
    - role: fubarhouse.curl
    
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    
    - role: geerlingguy.jenkins
    
    - role: geerlingguy.docker
      
  tasks:
    - name: Enable Jenkins port
      firewalld:
        port: "{{ jenkins_http_port }}/tcp"
        permanent: yes
        state: enabled
        
    - name: Enable trusted CA
      command: "update-ca-trust force-enable"
        
    - name: Make sure the folder exists (Red Hat)
      file:
        path: /etc/ssl/certs
        state: directory
        
    - name: Copy PEM into folder (Red Hat)
      copy:
        src: "{{ nexus_cert_file_temp_location }}"
        dest: "/etc/ssl/certs/{{ ssl_cert_name }}"
      
    - name: Creating link for particular certificate
      file:
        src: "/etc/ssl/certs/{{ ssl_cert_name }}"
        dest: "/etc/pki/ca-trust/source/anchors/{{ ssl_cert_name }}"
        state: link
      
    - name: Update trusted CA
      command: "update-ca-trust"
      
    - name: Restart Jenkins once installation completed
      service:
        name: jenkins
        state: restarted
      
    - name: Restart Docker
      service:
        name: docker
        state: restarted