---
- hosts: jenkins
  remote_user: vagrant
  become: yes
  
  roles:
    - role: fubarhouse.curl
    - role: geerlingguy.jenkins
        
- hosts: jenkins
  remote_user: vagrant
  become: yes
  tags: update
  
  vars:
    jenkins_config_url: "http://{{ inventory_hostname }}:{{ jenkins_http_port }}"
    jenkins_config_user: "{{ jenkins_admin_username }}"
    jenkins_config_password: "{{ jenkins_admin_password }}"
    
    jenkins_config_credentials:
      - kind: username_with_password
        id: docker-registry
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password_vault }}"
        description: Nexus Docker Registry
      - kind: ssh_username_with_private_key
        id: kubernetes-master
        username: "{{ jenkins_agent_user }}"
        private_key: "{{ lookup('file', '{{ ssh_private_key_local_path }}') }}"
        passphrase: ''
        description: SSH to Kubernetes master
        
    jenkins_config_global_environment_variables:
      - name: DOCKER_REGISTRY
        value: "{{ inventory_hostname }}:{{ nexus_https_docker_registry_port }}"
        
    jenkins_job_dsl_url: "http://{{ inventory_hostname }}:{{ jenkins_http_port }}"
    jenkins_job_dsl_user: "{{ jenkins_admin_username }}"
    jenkins_job_dsl_password: "{{ jenkins_admin_password }}"
    jenkins_job_dsl_content: "{{ lookup('file', 'jenkins-job-dsl-scripts/play-job.groovy') }}"
  
  pre_tasks:
    - name: Ensure Jenkins is up and running
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ jenkins_http_port }}"
        delay: 25
  
  roles:
   - meierw.jenkins_config
   - meierw.jenkins_job_dsl_exec
   
- hosts: jenkins_agents
  remote_user: vagrant
  become: yes
  
  vars:
    master_host: "{{ jenkins_host }}"
    master_username: "{{ jenkins_admin_username }}"
    master_password: "{{ jenkins_admin_password }}"
    slave_linux_jenkins_cred_id: kubernetes-master
    slave_linux_jenkins_username: "{{ jenkins_agent_user }}"
    slave_linux_jenkins_password: "{{ jenkins_agent_password }}"
    slave_linux_user_group: "{{ jenkins_agent_user }}"
    slave_agent_name: kubernetes_master
  
  roles:
    - role: lean_delivery.jenkins_slave
   
- hosts: jenkins
  remote_user: vagrant
  become: yes
  
  tasks:
    - name: Restart Jenkins once installation completed
      service:
        name: jenkins
        state: restarted