---
- hosts: jenkins
  remote_user: vagrant
  become: yes
  
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_install_compose: true
    docker_compose_version: "1.24.0-rc1"
    docker_users:
      - jenkins
  
  roles:
    - role: fubarhouse.curl
    
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    
    - role: geerlingguy.jenkins
    
    - role: geerlingguy.docker
      
  tasks:
    - name: Enable Jenkins port
      firewalld:
        port: "{{ jenkins_http_port }}/tcp"
        permanent: yes
        state: enabled
      become: yes
      
    - name: Restart Jenkins once installation completed
      service:
        name: jenkins
        state: restarted
      become: yes