---
- hosts: kubernetes
  remote_user: "{{ jenkins_os_user }}"
  become: yes
  
  vars:   
    swap_file_state: absent
    
  roles:
   - geerlingguy.swap
   
  post_tasks:
    - name: Set sysctl value for net.bridge.bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        
    - name: Copy custom flannel file on remote servers
      copy:
        src: "templates/kube-flannel.yml"
        dest: "/tmp/kube-flannel.yml"
        owner: "{{ jenkins_os_user }}"
        
- hosts: kubernetes_master
  remote_user: "{{ jenkins_os_user }}"
  become: yes
  
  vars:  
    kubernetes_role: "master"
    kubernetes_allow_pods_on_master: false
    kubernetes_apiserver_advertise_address: "{{ inventory_hostname }}"
    kubernetes_flannel_manifest_file: "/tmp/kube-flannel.yml"
    
  roles:
    - geerlingguy.kubernetes
    
  tasks:
    - name: "Move .kube config folder to {{ jenkins_os_user }} home directory"
      shell: "mv /root/.kube {{ jenkins_home }}.kube && chmod a+r /etc/kubernetes/admin.conf"
      
    - name: Fix permissions of .kube config dir
      file:
        path: "{{ jenkins_home }}.kube"
        owner: "{{ jenkins_os_user }}"
    
- hosts: kubernetes_nodes
  remote_user: vagrant
  become: yes

  vars:
    kubernetes_role: "node"
   
  roles:
    - geerlingguy.kubernetes