---
- hosts: nexus
  remote_user: vagrant
  become: yes
  
  vars:
    apache_listen_ip: "*"
    apache_listen_port_ssl: "{{ nexus_https_port }}"
    apache_create_vhosts: true
    apache_vhosts_filename: "nexus.conf"
    apache_vhosts_template: "nexus.conf.j2"
    apache_remove_default_vhost: true
    
    apache_vhosts_ssl:
      - servername: "nexus"
        documentroot: "/"
        certificate_file: "{{ nexus_ssl_cert_file }}"
        certificate_key_file: "{{ nexus_ssl_key }}"
    
    apache_state: started
    
    
    nexus_default_port: "{{ nexus_http_port }}"
    nexus_admin_password: "{{ nexus_admin_password_vault }}"
    nexus_delete_default_repos: true
    nexus_delete_default_blobstore: true
    
    nexus_blobstores:
      - name: docker
        path: "{{nexus_data_dir}}/blobs/docker"

    nexus_config_docker: true
    
    _nexus_repos_docker_defaults:
      blob_store: docker
      force_basic_auth: true
      strict_content_validation: true
      version_policy: mixed
      layout_policy: strict
      write_policy: allow
      
    nexus_repos_docker_hosted:
      - name: docker
        http_port: "{{ nexus_docker_registry_internal_port }}"
        v1_enabled: false
    nexus_repos_docker_proxy: []
    nexus_repos_docker_group: []
  
  roles:
    - role: wtanaka.rsync
    
    - { role: geerlingguy.apache }
    
    - { role: ansible-thoteam.nexus3-oss }
    
  post_tasks:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted