- src: geerlingguy.jenkins
- src: fubarhouse.curl
- src: geerlingguy.java
- src: wtanaka.rsync
- src: geerlingguy.apache
- src: ansible-thoteam.nexus3-oss
- src: geerlingguy.docker
- src: geerlingguy.kubernetes
- src: geerlingguy.swap
- src: geerlingguy.php
- src: meierw.jenkins_job_dsl_exec
- src: meierw.jenkins_config
- src: geerlingguy.git