---
jenkins_package_state: latest
jenkins_hostname: localhost
jenkins_home: /var/lib/jenkins
jenkins_plugins: [ cloudbees-folder,
                   antisamy-markup-formatter,
                   build-timeout,
                   credentials-binding,
                   timestamper,
                   ws-cleanup,
                   ant,
                   gradle,
                   junit,
                   workflow-aggregator,
                   github-organization-folder,
                   pipeline-stage-view,
                   build-pipeline-plugin,
                   conditional-buildstep,
                   jenkins-multijob-plugin,
                   parameterized-trigger,
                   copyartifact,
                   git,
                   git-parameter,
                   github,
                   subversion,
                   ssh-slaves,
                   matrix-auth,
                   pam-auth,
                   ldap,
                   email-ext,
                   mailer,
                   workflow-api,
                   workflow-step-api,
                   ssh-credentials,
                   credentials,
                   plain-credentials,
                   structs,
                   display-url-api,
                   token-macro,
                   lockable-resources,
                   pipeline-rest-api,
                   jquery-detached,
                   handlebars,
                   momentjs,
                   workflow-job,
                   workflow-scm-step,
                   github-branch-source,
                   scm-api,
                   pipeline-github-lib,
                   workflow-multibranch,
                   workflow-cps,
                   workflow-cps-global-lib,
                   branch-api,
                   script-security,
                   ace-editor,
                   workflow-support,
                   matrix-project,
                   maven-plugin,
                   run-condition,
                   git-client,
                   resource-disposer,
                   workflow-durable-task-step,
                   mapdb-api,
                   built-on-column,
                   apache-httpcomponents-client-4-api,
                   pipeline-input-step,
                   pipeline-graph-analysis,
                   jackson2-api,
                   pipeline-stage-step,
                   javadoc,
                   jsch,
                   durable-task,
                   github-api,
                   workflow-basic-steps,
                   jquery,
                   envinject,
                   git-server,
                   envinject-api,
                   pipeline-model-definition,
                   pipeline-build-step,
                   pipeline-milestone-step,
                   pipeline-model-api,
                   pipeline-model-extensions,
                   docker-workflow,
                   pipeline-model-declarative-agent,
                   pipeline-stage-tags-metadata,
                   docker-commons,
                   authentication-tokens,
                   job-dsl ]
jenkins_plugins_install_dependencies: true
jenkins_plugins_state: latest
jenkins_updates_url: "https://updates.jenkins.io"
jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"